### PR TITLE
Respect directive regex flags

### LINKED ISSUE #29: Simple docstrings are not recognized as valid RST
A simple example to reproduce:
```py
>>> text = """
... Spam.
...
... :param eggs: bacon.
... "
>>> import docstring_to_markdown
>>> docstring_to_markdown.looks_like_rst(text)
False
```
The reason is that the regex search in `docstring_to_markdown.looks_like_rst()` does not use the eventual flags from the directive. In the above example, the responsible directive has the multiline flag set:
https://github.com/python-lsp/docstring-to-markdown/blob/cceaeab642f38f48708e2b517659936532cc346e/docstring_to_markdown/rst.py#L131-L135
but the function never uses it:
https://github.com/python-lsp/docstring-to-markdown/blob/cceaeab642f38f48708e2b517659936532cc346e/docstring_to_markdown/rst.py#L341-L342

### PR DESCRIPTION
**Pull request by hoefling**
Closes #29.

### CODE REVIEW

**Comment by hoefling** [comment]
Python 3.6 went EOL a year ago, so not sure if it is worth to be kept in the pipeline. Nevertheless, I think I can extend the CI matrix if 3.6 is still necessary.

**Comment by krassowski** [comment]
If it causes problems, it's fine to drop 3.6.

**Comment by hoefling** [comment]
@krassowski it shouldn't be a problem, at least not until GH drops the `ubuntu-20.04` runners :sunglasses: I made a mistake in the previous commit, forgot to brace the single value for the os parameter in the matrix. The next run should be fine - I created a fake PR to test, [looking good](https://github.com/hoefling/docstring-to-markdown/actions/runs/4472823222).

**Review by krassowski — APPROVED** [review]
Thank you!

**Pull request merged**
